Repository Omniscient-Job-Project/Omniscient-Back, pull requests merged in 2024-09, with the labels that each got.

#1 "core"
  .idea/.gitignore
  .idea/BackServer.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Omniscient-Back/.gitignore
  Omniscient-Back/build.gradle
  Omniscient-Back/gradle/wrapper/gradle-wrapper.jar
  Omniscient-Back/gradle/wrapper/gradle-wrapper.properties
  Omniscient-Back/gradlew
  Omniscient-Back/gradlew.bat
  Omniscient-Back/settings.gradle
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/OmniscientBackApplication.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/controller/CurationController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/infra/CurationInfra.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/model/Curation.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/model/CurationDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/repository/CurationRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/service/CurationService.java
  Omniscient-Back/src/main/resources/application.properties
  Omniscient-Back/src/test/java/com/omniscient/omniscientback/OmniscientBackApplicationTests.java
Labels: documentation

#3 jobApi
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/repository/JobRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/WebConfigurer.java
Labels: 진행중

#4 feat:naverlogin,curationAPI
  Omniscient-Back/build.gradle
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/controller/CurationController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/model/Curation.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/model/CurationDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/repository/CurationRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/service/CurationService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/naver/controller/NaverController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/naver/controller/NaverProperties.java
  Omniscient-Back/src/main/resources/application.properties
  Omniscient-Back/src/main/resources/application.yml
Labels: 진행중

#6 fix:curation
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/controller/CurationController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/repository/CurationRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/service/CurationService.java
Labels: 진행중

#7 feat:config
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SecurityConfig.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/WebConfigurer.java
Labels: 진행중

#8 배포준비
  .idea/.gitignore
  .idea/BackServer.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Omniscient-Back/build.gradle
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/repository/JobRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/controller/CurationController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/model/Curation.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/model/CurationDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/repository/CurationRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/service/CurationService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SecurityConfig.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/WebConfigurer.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/naver/controller/NaverController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/naver/controller/NaverProperties.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/Visitor.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/VisitorController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/VisitorRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/VisitorService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/controller/NoticeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/Notice.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/NoticeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/repository/NoticeRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/service/NoticeService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/controller/UserController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/model/Role.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/model/User.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/model/UserDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/repository/UserRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/service/UserService.java
  Omniscient-Back/src/main/resources/application.properties
  Omniscient-Back/src/main/resources/application.yml
Labels: 진행중

#10 fix:jobAPI
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobService.java
Labels: 진행중

#13 update profile
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/infra/ProfileInfra.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Profile.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ProfileDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/ProfileRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ProfileService.java
Labels: 진행중

#14 update Resume
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ResumeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Resume.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ResumeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/ResumeRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ResumeService.java
Labels: 진행중

#16 update length
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Resume.java
Labels: 진행중

#17 feat:login
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SecurityConfig.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/SignupDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserRole.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/repository/UserRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#19 update crud
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/controller/UserController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/model/Role.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/model/User.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/model/UserDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/repository/UserRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/user/service/UserService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ResumeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Profile.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ProfileDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Resume.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ResumeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/ProfileRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/ResumeRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ProfileService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ResumeService.java
Labels: 진행중

#20 feat:잡아바API
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/JobabaAPI/controller/JobabaApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/JobabaAPI/model/JobabaDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/JobabaAPI/model/JobabaEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/JobabaAPI/repository/JobabaRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/JobabaAPI/service/JobabaService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobService.java
Labels: 진행중

#23 update Certificate crud
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/CertificateController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Certificate.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/CertificateDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/CertificateRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/CertificateService.java
Labels: 진행중

#25 fix:jobAPI
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/JobabaAPI/service/JobabaService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobabaApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobTotalDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobabaDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/model/JobabaEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/repository/JobabaRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobabaService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/controller/CurationController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/infra/CurationInfra.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/model/Curation.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/model/CurationDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/repository/CurationRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/curation/service/CurationService.java
Labels: 진행중

#27 fix:login/signup
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/repository/UserRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#29 feat gradejob
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradejob/controller/GradeApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradejob/model/GradeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradejob/model/GradeEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradejob/repository/GradeApiRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradejob/service/GradeApiService.java
Labels: 진행중

#30 feat testapi
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/controller/TestApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/model/TestDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/model/TestEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/repository/TestApiRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/service/TestApiService.java
Labels: 진행중

#31 commit -m "feat : manager_FAQ"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/controller/VisitorController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/model/Visitor.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/repository/VisitorRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/service/VisitorService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/controller/FaqController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/Faq.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/FaqDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/repository/FaqRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/service/FaqService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/controller/NoticeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/Notice.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/NoticeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/service/NoticeService.java
Labels: 진행중

#32 board crud
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/controller/BoardController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/infra/BoardInfra.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/model/Board.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/model/BoardDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/repository/BoardRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/service/BoardService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/CertificateController.java
Labels: 진행중

#33 fix grade
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradeapi/controller/GradeApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradeapi/model/GradeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradeapi/model/GradeEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradeapi/repository/GradeApiRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradeapi/service/GradeApiService.java
Labels: 진행중

#34 fix testapi
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/controller/TestApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/model/TestEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/service/TestApiService.java
Labels: 진행중

#35 feat site_api
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/controller/SiteApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/model/SiteDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/model/SiteEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/repository/SiteApiRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/service/SiteApiService.java
Labels: 진행중

#37 fix:login/signup
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/JwtService.java
Labels: 진행중

#38 git commit -m "fix : nullable, status 변경"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/controller/FaqController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/Faq.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/FaqDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/repository/FaqRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/service/FaqService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/controller/NoticeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/Notice.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/NoticeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/service/NoticeService.java
Labels: 진행중

#39 git commit -m "fix : 삭제상태, 기본생성자, 오토와이어드"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/model/Visitor.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/controller/FaqController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/Faq.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/FaqDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/controller/NoticeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/Notice.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/NoticeDTO.java
Labels: 진행중

#40 fix "delete status & getter&setter"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/controller/BoardController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/model/Board.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/model/BoardDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/repository/BoardRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/service/BoardService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/CertificateController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ResumeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Certificate.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/CertificateDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Profile.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ProfileDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Resume.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ResumeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/CertificateRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/CertificateService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ProfileService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ResumeService.java
Labels: 진행중

#41 fix:jobabaController
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobabaApiController.java
Labels: 진행중

#42 update:TestApi Controller
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/controller/TestApiController.java
Labels: 진행중

#43 git commit -m "feat : import notice and FAQ from admin"
  Omniscient-Back/build.gradle
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/controller/NoticeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/Notice.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/model/NoticeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/service/NoticeService.java
Labels: 진행중

#44 updateResume
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ResumeController.java
Labels: 진행중

#45 fix:login token
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/JwtAuthenticationFilter.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SecurityConfig.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/exception/JwtTokenException.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/JwtTokenDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/SignupDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/repository/UserRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/ExpireTime.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/JwtService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/JwtTokenProvider.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#46 commit -m "fix : 조회수 수정"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/model/Visitor.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/controller/FaqController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/Faq.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/FaqDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/service/FaqService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/controller/NoticeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/service/NoticeService.java
Labels: 완료

#47 Comment crud
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/controller/CommentController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/infra/CommentInfra.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/model/Comment.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/model/CommentDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/repository/CommentRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/service/CommentService.java
Labels: 진행중

#48 fix:logout
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/JwtTokenProvider.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#49 feat:dockerfile
  Omniscient-Back/Dockerfile
Labels: 진행중

#50 feat:swagger config
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SwaggerConfig.java
Labels: 진행중

#51 fix gradeApiController
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradeapi/controller/GradeApiController.java
Labels: 진행중

#52 update: end point
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradeapi/controller/GradeApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobabaApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/controller/BoardController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/controller/CommentController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/WebConfigurer.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/controller/VisitorController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/controller/FaqController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/controller/NoticeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/CertificateController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ResumeController.java
Labels: 진행중

#53 feat: FTP server
  Omniscient-Back/build.gradle
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/controller/FtpController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/service/FtpImgLoaderUtil2.java
Labels: 진행중

#54 update: FTP, jobaba 주석추가
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobabaApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/controller/FtpController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/service/FtpImgLoaderUtil2.java
Labels: 진행중

#55 update: job 주석추가
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobApiController.java
Labels: 진행중

#58 update: ftp config
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/service/FtpImgLoaderUtil2.java
Labels: 진행중

#59 "fix board & profile"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/controller/BoardController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/model/BoardDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Profile.java
Labels: 진행중

#60 fix Validation SiteController
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/controller/SiteApiController.java
Labels: 진행중

#61 fix Service & Controller Validation
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/controller/TestApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/service/TestApiService.java
Labels: 진행중

#62 update: SecurityConfig, docker, fptcontroller
  Omniscient-Back/Dockerfile
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/controller/FtpController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SecurityConfig.java
Labels: 진행중

#63 update: 라이브러리
  Omniscient-Back/build.gradle
Labels: 진행중

#64 배포
  Omniscient-Back/Dockerfile
  Omniscient-Back/build.gradle
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/controller/SiteApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/controller/TestApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/service/TestApiService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/controller/BoardController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/model/BoardDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/controller/FtpController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/service/FtpImgLoaderUtil2.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SecurityConfig.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Profile.java
Labels: 진행중

#66 fix: login token
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/ExpireTime.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/JwtTokenProvider.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#67 git commit -m "fix:메인페이지 방문자수,회원수"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/UserController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/repository/UserRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/UserService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/controller/VisitorController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/model/Visitor.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/repository/VisitorRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/service/VisitorService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/controller/NoticeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/service/NoticeService.java
Labels: 진행중

#68 fix: site api, userentity
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/controller/SiteApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserEntity.java
Labels: 진행중

#69 feat categoryapi
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradeapi/controller/GradeApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/gradeapi/service/GradeApiService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/controller/SiteApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/model/SiteDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/model/SiteEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/repository/SiteApiRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/siteapi/service/SiteApiService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/controller/TestApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/model/TestDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/model/TestEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/service/TestApiService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/WebConfigurer.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserEntity.java
Labels: 진행중

#70 feat image
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Profile.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ProfileDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ProfileService.java
Labels: 진행중

#71 feat employmentapi
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/employmentapi/controller/EmploymentApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/employmentapi/model/EmploymentDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/employmentapi/model/EmploymentEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/employmentapi/repository/EmploymentRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/employmentapi/service/EmploymentService.java
Labels: 진행중

#72 fix:login token
  Omniscient-Back/build.gradle
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/exception/GlobalExceptionHandler.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/exception/UserNotFoundException.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/JwtTokenProvider.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#73 git commit -m "fix : 공지사항, FAQ"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SecurityConfig.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/UserController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/model/UserRole.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/UserService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/controller/FaqController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/notice/controller/NoticeController.java
Labels: 완료

#75 fix: swagger
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SecurityConfig.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/WebConfigurer.java
Labels: 완료

#76 fix: WebConfigurer
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/WebConfigurer.java
Labels: 완료

#77 fix:find_id/password
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/EmailService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#78 update: Dockerfile
  Omniscient-Back/Dockerfile
Labels: 진행중

#79 update: Dockerfile
  Omniscient-Back/Dockerfile
Labels: 진행중

#80 fix:find_password
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#81 fix: 트랜젝션
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobabaService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/service/BoardService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/service/CommentService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/CertificateService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ProfileService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ResumeService.java
Labels: 진행중

#82 commit -m "fix : 방문자수"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/controller/VisitorController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/service/VisitorService.java
Labels: 완료

#83 update: Board
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/controller/BoardController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/infra/BoardInfra.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/model/Board.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/model/BoardDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/board/service/BoardService.java
Labels: 진행중

#84 update: Comment
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/controller/CommentController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/infra/CommentInfra.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/model/Comment.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/model/CommentDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/repository/CommentRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/comment/service/CommentService.java
Labels: 진행중

#85 update: Certificate
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/CertificateController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Certificate.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/CertificateDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/CertificateService.java
Labels: 진행중

#86 fix : 보안 배열 합침.
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/SecurityConfig.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/global/config/WebConfigurer.java
Labels: 진행중

#87 update: Profile
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Profile.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ProfileDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ProfileService.java
Labels: 진행중

#88 update: Resume
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ResumeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Resume.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ResumeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ResumeService.java
Labels: 진행중

#89 fix: mypage
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/CertificateRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/ProfileRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/ResumeRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/CertificateService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ProfileService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ResumeService.java
Labels: 진행중

#90 git commit -m "fix : faq, visitor id 수정"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/controller/VisitorController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/model/Visitor.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/repository/VisitorRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/admin/visitor/service/VisitorService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/controller/FaqController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/Faq.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/model/FaqDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/repository/FaqRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/manager/faq/service/FaqService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/CertificateController.java
Labels: 완료

#91 update: job api logger
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobabaApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobabaService.java
Labels: 진행중

#92 update readme
  README.md
Labels: 진행중

#93 update readme
  README.md
Labels: 진행중

#94 fix readme
  README.md
Labels: 진행중

#95 Update README.md
  README.md
Labels: 완료

#96 update: JobabaApiController endpoint, testcode
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobabaApiController.java
  Omniscient-Back/src/test/java/com/omniscient/omniscientback/api/jobApi/JobabaApiControllerTest.java
Labels: 진행중

#98 update: JobabaApiController detail
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobabaApiController.java
Labels: 진행중

#99 fix: logger 제거, 테스트코드
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/controller/JobabaApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/controller/FtpController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/ftpserver/service/FtpImgLoaderUtil2.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/CertificateController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ResumeController.java
  Omniscient-Back/src/test/java/com/omniscient/omniscientback/api/jobApi/JobabaApiControllerTest.java
Labels: 진행중

#100 fix: logger 제거
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/jobApi/service/JobabaService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/CertificateService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ResumeService.java
Labels: 진행중

#101 fix: login
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#102 feat categoryapi
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/categoryapi/controller/CategoryController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/categoryapi/model/CategoryDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/categoryapi/model/CategoryEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/categoryapi/repository/CategoryRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/categoryapi/service/CategoryService.java
Labels: 진행중

#103 commit -m "fix : 유저삭제기능"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/UserController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/UserService.java
Labels: 진행중, 완료

#104 fix localDate
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/controller/TestApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/model/TestDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/model/TestEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/service/TestApiService.java
Labels: 진행중

#108 feat 시험일정 테스트코드
  Omniscient-Back/src/test/java/com/omniscient/omniscientback/api/testapi/TestApiControllerTest.java
Labels: 진행중

#110 fix "img"
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/FileUploadController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/UserProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/FileUpload.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/FileUploadDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Profile.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ProfileDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/UserProfile.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/UserProfileDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/FileUploadRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/ProfileRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/UserProfileRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/FileUploadService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ProfileService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/UserProfileService.java
Labels: 진행중

#111 fix testapi & testcode
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/api/testapi/controller/TestApiController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/CertificateController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/FileUploadController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/ResumeController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/controller/UserProfileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/infra/ProfileInfra.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Certificate.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/CertificateDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/FileUpload.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/FileUploadDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/Resume.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/ResumeDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/UserProfile.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/model/UserProfileDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/CertificateRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/FileUploadRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/ResumeRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/repository/UserProfileRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/CertificateService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/FileUploadService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/ResumeService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/service/UserProfileService.java
  Omniscient-Back/src/test/java/com/omniscient/omniscientback/api/testapi/TestApiControllerTest.java
Labels: 진행중

#112 fix mypage Profile
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/fileupload/controller/FileUpLoadController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/fileupload/model/FileUpLoadDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/fileupload/model/FileUpLoadEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/fileupload/repository/FileUpLoadRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/fileupload/service/FileUpLoadService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/profile/controller/ProFileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/profile/model/ProFileDTO.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/profile/model/ProFileEntity.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/profile/repository/ProFileRepository.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/profile/service/ProFileService.java
Labels: 진행중

#115 feat:adminLogin
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/LoginController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/controller/SignupController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/login/service/SignupService.java
Labels: 진행중

#122 fix profile & utils
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/profile/controller/ProFileController.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/mypage/profile/service/ProFileService.java
  Omniscient-Back/src/main/java/com/omniscient/omniscientback/utile/Utils.java
Labels: 진행중
